[package]
name = "pokerbot"
authors = ["29 <791603901@qq.com>"]
version = "0.0.1"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["nlh", "holdem", "gameplay", "ai", "terminal"]
categories = ["command-line-utilities", "game-development", "games", "mathematics", "simulation"]
repository = "https://github.com/czy-29/pokerbot"
homepage = "https://github.com/czy-29/pokerbot"
description = """
ğŸš§ A Texas Hold'em Heads up pokerbot game binary and library abstraction (WIP, nothing usable for now).
"""
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Because we utilized the `explicitly inferred arguments to const generics` feature.
# å› ä¸ºæˆ‘ä»¬ä½¿ç”¨äº†â€œæ˜¾å¼æ¨æ–­çš„å¸¸é‡æ³›å‹å‚æ•°â€ç‰¹æ€§ã€‚
# https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#explicitly-inferred-arguments-to-const-generics
rust-version = "1.89.0"

[package.metadata.docs.rs]
all-features = true

[dependencies]
est = { version = "0.10.0", features = ["slice"] }
itertools = "0.14.0"
rand = "0.9.2"
rayon = "1.10.0"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "sync"] }

[dev-dependencies]

[build-dependencies]
version_check = "0.9.5"

[features]
